### ISSUE TITLE
Crash with Forestry 4.0

### ISSUE THREAD

**Issue by EXTER7** [MagicBees/MagicBees#104]
Using Magic Bees 2.3.6 and Forestry 4.0.2

This crash happened a few seconds after loading my world:
http://pastebin.com/S6cYxZXZ

**Comment by mezz** [comment]
Yeah looks like it's still not compatible with Forestry 4. I may poke at it soon

**Comment by AlexPlus117** [comment]
I have the same problem with Forestry 4.0.3 and Magic Bees 2.3.6. When will be the fix out?

**Comment by AlexPlus117** [comment]
I have the same problem with Magic Bess 2.3.6, Forestry 4.0.3 and GenDustry. Here's the report: http://pastebin.com/PGAKPMX8

**Comment by mezz** [comment]
PR for this issue: https://github.com/MagicBees/MagicBees/pull/106

**Comment by MysteriousAges** [comment]
PR merged; will push a 4.0 compatible build to Curse soon.

**Comment by AlexPlus117** [comment]
Could you switch the version from beta to release, because Curse doesn't see beta version unless I tell  it to do so.

**Comment by MysteriousAges** [comment]
It lists betas on the Minecraft CurseForge domain: http://minecraft.curseforge.com/projects/magic-bees

**Comment by mezz** [comment]
@MysteriousAges can you change it to a release version? Forestry 4 is the default stable release now.
