### ISSUE TITLE
Curse doesn't recognize forestry as a dependency

### ISSUE THREAD

**Issue by natedogith1** [MagicBees/MagicBees#114]

**Comment by MysteriousAges** [comment]
I have no idea how to set that. :\

**Comment by mezz** [comment]
I only just figured this out like.. yesterday. When you set it on the latest file, it counts for the whole project. Very dumb interface, but it works.

**Comment by mezz** [comment]
Looks like myst fixed it, Forestry is listed as a dependency now.
http://minecraft.curseforge.com/projects/magic-bees/relations/dependencies
