### ISSUE TITLE
Botania  flower recipes need updating

### ISSUE THREAD

**Issue by Zsashas** [MagicBees/MagicBees#116]
Mana Petals no longer exist, instead Vazkii added Mana Powder, and simplified a lot of recipes. I'm surprised that viewing the broken recipes doesn't cause a crash or something, honestly.

In the Lexica Botania, the recipe simply has blank spaces, while in NEI it shows Fire in those spots.

https://gyazo.com/6d198c30f7eea0fc8e261a2d83c1313d
https://gyazo.com/2c6f0923b019eaec74a25c7ecbf0267b

**Comment by MysteriousAges** [comment]
PR #115 will solve this.

**Comment by MysteriousAges** [comment]
Closed by #115
