### ISSUE TITLE
Vis Apiary Booster not working

### ISSUE THREAD

**Issue by JasonMcRay** [MagicBees/MagicBees#120]
> I built the vis apiary booster and set it up according to MysteriousAge's video (https://youtu.be/dk_0uDVedNI) but it doesn't do anything. It doesn't even pull centi-vis from my energized node. 

MagicBees: 2.4.0
Modpack: Infitech 2

**Comment by MysteriousAges** [comment]
Do you have a screenshot of your setup? I believe you need at least one vis relay between the node and the booster for it to function.

**Comment by Timeslice42** [comment]
I even went so far as to try and duplicate exactly what you had in the video, including setting the relays to red (which I didn't expect to help). I'll attach a screenshot shortly.

**Comment by Timeslice42** [comment]
This is what it ended up looking like in my play world: https://imgur.com/a/p75cf

**Comment by MysteriousAges** [comment]
Are there any bees working in any of the 4 apiaries?

**Comment by Timeslice42** [comment]
There are usually magic bees in them, but in that screenshot they happened to be empty.

**Comment by Timeslice42** [comment]
Oops, sorry, I lied. There were/are ethereal drones active in the bottom left magic apiary.

**Comment by Verharn** [comment]
MagicBees: 2.4.0
Modpack: Infitech 2

https://youtu.be/lRzrcITOTUo

**Comment by Timeslice42** [comment]
Thanks for that :)

**Comment by Fabboz** [comment]
can you make an update for the 3.6.2 version for them who use forestry 3.6.12?
