### ISSUE TITLE
Researching things that you shouldn't be able to research

### ISSUE THREAD

**Issue by Zobody** [MagicBees/MagicBees#121]
You can research Vis Apiary Booster without researching Arcane Bore, which is in the receipe.

**Comment by MysteriousAges** [comment]
Uh, the apiary booster should not be depending on the Arcane Bore _at all_... I'll take a look.

**Comment by Timeslice42** [comment]
lol, really? Yeah, it takes four arcane bores to craft. I'm starting to wonder if you're using a different repository than the rest of us, Myst. :P

**Comment by MysteriousAges** [comment]
Missed an Enum constant to shift greatwood planks to the right metadata value because apparently there are two values for pressure plates. Thanks, Az.
