### ISSUE TITLE
Server Crash after updating from 2.4.0 to 2.4.1

### ISSUE THREAD

**Issue by Drethic** [MagicBees/MagicBees#123]
I just updated my modpack with 2.4.1 and on Local and Server launch I received this crash:

http://pastebin.com/uxALdfrr

Let me know if you need any more information.

**Comment by ericcotelnu** [comment]
I got nothing to add, except that I get the same exact crash. Reverting to 2.4.0 in my private modpack for now.

**Comment by Horneat** [comment]
i get the same crash

**Comment by CandiceJoy** [comment]
Same crash for me.

http://pastebin.com/jAJBxefg
