### ISSUE TITLE
Crash from null EE3 bee specialty products

### ISSUE THREAD

**Issue by chrisay** [MagicBees/MagicBees#124]
Appears identical to error #123 – issues persist for both versions 2.4.1 and 2.4.2.
Reverting to 2.4.0 resolves the issue.

http://pastebin.com/qqpdgRSY

Forge: 10.13.4.1566
Forestry: 4.2.5.53

**Comment by Horneat** [comment]
i have the same Crash

**Comment by ThexXTURBOXx** [comment]
Well, looks like the crash is related to MultiMC as well.
I would try to update forge (there is a update available) and forestry (there you are several version behind...)

**Comment by mezz** [comment]
This doesn't have to do with MultiMC, forge, etc.

@MysteriousAges it looks like you fixed this just after the 2.4.2 release, it's working in dev. Can you make a new release?

**Comment by MysteriousAges** [comment]
Uploaded file to Curse.
