### ISSUE TITLE
Botania recipes broken

### ISSUE THREAD

**Issue by Bennyboy1695** [MagicBees/MagicBees#126]
On infinity version 2.3.5 any recipes added by magic bees that contain mana petals in the recipes have broken an in replace of the mana petals is minecraft fire.

http://goo.gl/OPp9Ey
http://goo.gl/8iHzbH
http://goo.gl/Xtq8nD

**Comment by Bennyboy1695** [comment]
Just found out thats its caused by mana petals being removed from botania bild 1.8-238 which has caused the issue

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest version of Magic Bees.
Duplicate of #116
