### ISSUE TITLE
Withering Bee does not produce anything

### ISSUE THREAD

**Issue by 2ndkirbyever** [MagicBees/MagicBees#134]
I recently updated Magic Bees to 2.4.3, and the first thing I noticed is that when I run my withering bee through a Gendustry apiary, it does not produce any wither skeleton bone chips. Normally, when I run that bee through the apiary with 8 production upgrades, it gives me enough bone chips to make one skull. I am using Forestry 4.2.11.59, Binnie Patcher 1.6 with Binnie's Mods 2.0-pre14, and Gendustry 1.6.3.132 along with Magic Bees. I appreciate any help provided. Thank you.

**Comment by grydian** [comment]
Make you have the temperature and humidity exactly how the bees like it.  In the newer versions of forestry the bees require the exact biome conditions they want to get the specialty items.

**Comment by mezz** [comment]
Please see this issue for a full explanation: https://github.com/MagicBees/MagicBees/issues/128
