### ISSUE TITLE
Possibility to disable certain species

### ISSUE THREAD

**Issue by JasonMcRay** [MagicBees/MagicBees#135]
Would it be possible to let us disable certain bee species? For example Osmium bees. They not too hard to make and are producing high end material (Osmium is high end material in GregTech).

Thank you very much

**Comment by mezz** [comment]
You should be able to use Forestry's species blacklist at the bottom of `config/forestry/apiculture.cfg`. You can dump a list of species ids with an in-game command, I think it's `/forestry bee save`

**Comment by JasonMcRay** [comment]
Oh cool. Thanks Mezz.

What will happen with existing bees when blacklisted? Will they still be in-game? Or will they get removed?

**Comment by mezz** [comment]
If there are existing bees, they will probably show up as invalid alleles and crash. You can have it clear the bees with invalid alleles by setting `genetics.clear.invalid.chromosomes` in `forestry/comon.cfg`. It should make them into Forest bees I think.
