### ISSUE TITLE
All three specialty hives are missing

### ISSUE THREAD

**Issue by whitestarx0312** [MagicBees/MagicBees#140]
I'm using:
Forestry: forestry_1.7.10-4.2.12.60
Magic Bees: magicbees-1.7.10-2.4.3

I was working on a bee line and found that I needed the Infernal bee. I've done this a million times but I noticed that this time there were no Infernal hives located in my world, nor the creative tab/NEI. Additionally, abyssal and oblivion hives are failing to be in the world.  I also tried installing Binnie's mods/fix to see if I needed that but it didn't change anything. Unusual, Curious, and Resonating hives are all spawning. I haven't dabbled with the config at all either.

**Comment by grydian** [comment]
Infernal hives spawn in the nether, Oblivion hives span in the end and attuned hives spawn in magical biomes.  I tend to use the thaumcraft biome to get my attuned bees.

**Comment by whitestarx0312** [comment]
Yes I know where they spawn, but with the latest versions of the mod the hives are not showing up in game at all. They are not available via NEI or the creative menu. They do not exist in my instance.

**Comment by whitestarx0312** [comment]
Tried to start a new instance with just Forestry, Gendustry, Magic Bees, Binnies mods/fix and ThaumCraft but the bug persists, the hives are not in the game.

**Comment by mezz** [comment]
The hives are hidden from the creative menu and NEI.

**Comment by grydian** [comment]
I am using both the forestry and magic bees that you are.  And the binnie's mod patch.  I am getting all the spawns without problems.  Check to make sure the log shows them spawning and double check the configs.  It can help verify that they are infact not spawning.  Going to the nether should show up in log if you turn the debug feature on.  The line you need to have is logHiveSpawns=true  That should at least help narrow down the problem.  Also what version of Forge are you using?  Finally did you go to the end and see if oblivion hives are spawning under the island?  Maybe create a test world and jump to the end real quick and check for oblivion hives.

**Comment by whitestarx0312** [comment]
Hmm okay the ones in the end are there, I just assumed since I couldn't find the nether/deep hives and they weren't in NEI/Creative that they were messing up. Sorry for this!
