### ISSUE TITLE
[1.12.2] Crash with Forestry 5.7.0.x

### ISSUE THREAD

**Issue by frank89722** [MagicBees/MagicBees#158]
Game crash on startup

crash report: https://pastebin.com/HHrgXD7s

**Comment by kingofrunes** [comment]
I'm also seeing this issue

**Comment by SnowShock35** [comment]
Same issue here for me too. cc @mezz

**Comment by DeadSix27** [comment]
@SnowShock35 No need to notify mezz.. Nedelosk maintains MagicBees and he already fixed the issue (indev): https://github.com/ForestryMC/MagicBees/commits/1.12

**Comment by SnowShock35** [comment]
@DeadSix27 Apologies for using the wrong repository. I had forgotten that they moved it to the Forestry team. However, I had notified mezz since he push rights on the curseforge project. Nedelosk does not.

**Comment by mezz** [comment]
Uploaded a new Magic Bees build to Curse with Nedelosk's fix

**Comment by SnowShock35** [comment]
@mezz Thank you :heart:
