### ISSUE TITLE
Hives not even in the game?!

### ISSUE THREAD

**Issue by mezz** [MagicBees/MagicBees#21]
The Infernal, Oblivion and Deep hives are completely missing from our server and games. They dont even show up on NEI and I am kinda getting worried

**Comment by MysteriousAges** [comment]
Those three hives don't show up in NEI. Find a magic biome, quarry it some, and then complain about there being too many hives instead.

**Comment by mezz** [comment]
@MysteriousAges there are too many hives! https://github.com/MagicBees/MagicBees/issues/20
haha

**Comment by coderjcronin** [comment]
If you're really worried whether or not hives are spawning, turn on the logging option in the config.
