### ISSUE TITLE
Idea for Tainted Bees (if this doesn't already exist in some form)

### ISSUE THREAD

**Issue by mezz** [MagicBees/MagicBees#26]
This idea stems from something one of my testers ran across within a Tainted lands, a Meadows Bee hive covered in tainted tendrils with tainted grass growing on it.

Idea, Add Tainted Bee as a bee type. For the life of me I cannot remember if they are already there or not :p

The bees hives would only spawn in tainted lands OR could only be obtained via a world effect like a hive (any type really) being infected by a tainted biome.

The bees Effects:
* Negative Area Effect to npc/pcs - a percentage chance per x ticks to A) Inflict Taint Infection (if that is still a thing) and/or B) Add to players Flux/Taint counters.
* World Effect: When put into player made containers (Bee Houses, Apiaries, etc.) the bees "consume" surrounding taint (Fibrous Taint, Crusted Taint, etc.) to make some sort of tainted comb, this would/could be used as a way to fight or contain taint.
* Holding the bees or princesses within a players inventory could have a VERY low chance of infecting the player with taint

the Bees could produce a very low chance at thaumium nuggets, various shards, and/or amber (maybe in a chunk form), as well as some sort of tainted comb.

the comb could have the same ability as tainted items do when held in a player inventory, such as having a chance to dissolve down and infecting the player.

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-10-21 22:24:30+00:00_

Sounds cool.

 I could add it to my list of upcoming bees if you can provide more details like suggested breeding trees, colorschemes, products etc

**Comment by mezz** [comment]
_From Sean Hall on 2014-10-22 05:56:20+00:00_

Okay that took me a bit but here is a outline if you want anything more specific let me know and I will try and work on it some more:

https://docs.google.com/document/d/1by0bFwnv7JW_4rOtPhvmoDNB4M8ZXuF5IQO6uN_3s_A/edit?usp=sharing

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-12-17 01:15:12+00:00_

Going to try to set all bee additions as a milestone for 2.1.24.
Hopefully I will be able to finish them in one version

**Comment by MysteriousAges** [comment]
Tainted bees implemented to affect thaumcraft nodes. Probably won't be using these ideas for now.
