### ISSUE TITLE
Implement Thaumic Apiary

### ISSUE THREAD

**Issue by MysteriousAges** [MagicBees/MagicBees#32]
Thaumic Apiary

Features:
* Consumes Vis from source to:
  * Increase work speed
  * Increase mutation chance at Queen death
* Must be able to exist without requiring Thaumcraft.

Further questions:
* Should it accept frames?.
* Base work speed == Forestry Apiary?
* Increase rate of work speed/mutation chance?

**Comment by Vexatos** [comment]
No frames, Vis replaces frames.

How about it accepting vis and essentia, depending on the task?
- Aer Vis for work speed
- Permutatio Essentia for mutation chance
- Venenum Essentia to make them die more quickly AND to make Venenum actually have a use

How about that?

**Comment by MysteriousAges** [comment]
Closed by 55f9e58297d77bed55e83e7a5a586bceedecc48f

**Comment by mezz** [comment]
Nice!
