### ISSUE TITLE
Bees initializing without supported mods' items/blocks

### ISSUE THREAD

**Issue by ShawnRHayes** [MagicBees/MagicBees#36]
http://pastebin.com/EEscfk76

**Comment by blockbreaker1361** [comment]
http://pastebin.com/xpxjnUPA

I got the same thing.

**Comment by ultrasn0w** [comment]
Can confirm the same thing, seems to be an compatibility issue with Gendustry.
Works fine with versions older than 2.2.1.

**Comment by bdew** [comment]
One of your mutations crashes when getSpecialConditions is called

Gendustry 1.4.10 will log the exception instead of letting it crash the game

**Comment by MysteriousAges** [comment]
Commit 54faf63 should resolve this; if anyone has a new stack trace to confirm the issue, that would be helpful.

**Comment by MysteriousAges** [comment]
Please try with 2.2.2, see if it still occurs.
