### ISSUE TITLE
[NEI Addons Integration] Tree breeding bug

### ISSUE THREAD

**Issue by whitestarx0312** [MagicBees/MagicBees#37]
When installed alongside Magic Bees, the tree breeding information in NEI Addons breaks. The author pointed out the error here: https://github.com/bdew/neiaddons/issues/26

I am using the latest Magic Bees/Forestry/NEI Addons and it is still a recurring bug.

**Comment by MysteriousAges** [comment]
Please retry with 2.2.2, see if it still occurs.
