### ISSUE TITLE
[Botania Crash]

### ISSUE THREAD

**Issue by whitestarx0312** [MagicBees/MagicBees#42]
Magic Bees: 2.2.3
Forge: forge-10.13.2.1352
*I am using Optifine and Fastcraft, but I don't think they are related to this.

Crashlog: http://pastebin.com/kGx32xUG

**Comment by MysteriousAges** [comment]
Are you using any other bee-related mods, or mods that might change bees aside from Forestry?

Also, which Forestry version?

**Comment by Barhandar** [comment]
Same crash. I'm also using Binnie's Mods (2.0pre8, same as OP) and Gendustry 1.4.10.77.

I've got Forestry 3.5.3.11, OP's got 3.5.4.13.

**Comment by whitestarx0312** [comment]
Im using Forestry, Binnies mods, Magic Bees.
Forestry: 3.5.4.13

**Comment by MysteriousAges** [comment]
I bet I got the Extra Bees species names wrong. >_<

**Comment by MysteriousAges** [comment]
Yup, got the names wrong. Fix will be in next build. Until then, use 2.2.2. (Or don't use the Hiveacynth. Either works.)
