### ISSUE TITLE
Make the tempus aspect public instead of private, possibly move into API [Moved from BitBucket]

### ISSUE THREAD

**Issue by Mortvana** [MagicBees/MagicBees#44]
Not only logical, but will prevent (well reduce until an API to get it exists, but whatever) hacky reflection things I will have to do in my mod to use tempus in an infusion crafting (if MB is installed)
EDIT: Fixed small 8am typo

**Comment by MysteriousAges** [comment]
The issue with this is by having a reference to it in an API file, I will have to include the TC API Aspect class in the MB final package.

How about an Object ref you can cast to Aspect yourself that may or may not be null?

**Comment by MysteriousAges** [comment]
@Mortvana: take a look here: https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/api/MagicBeesAPI.java#L12

**Comment by Mortvana** [comment]
Thanks a lot, I am fine having to cast it to an aspect, a non-hacky way of referencing it is what I wanted, this will work great, my good apimancer.

**Comment by mezz** [comment]
Is it possible to use @Optional magic here? Something like an optional method getTempusAspect()
