### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Dream-Master** [MagicBees/MagicBees#45]
MC crash with forestry_1.7.10-3.6.0.539-unstable, binnie-mods-2.0-pre8 and magicbees-1.7.10-2.2.3

https://gist.github.com/Dream-Master/db9aeb7cbff2d8d74cfc#file-gistfile1-txt

Posted at binnies Bitbucket too
https://bitbucket.org/binnie567/binnie-mods/issue/227/crash-server

with forestry_1.7.10-3.6.0.536-unstable it works well

**Comment by MysteriousAges** [comment]
This is an Extra Bees crash. Can't help you here.
