### ISSUE TITLE
Pressing "u" in NEI crashes the game!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MagicBees/MagicBees#50]
Apparently it's a MagicBees issue: https://github.com/Vazkii/Botania/issues/826

**Comment by Corvorosso** [comment]
i have the same issue only when i put together MagicBees 2.3 and Botania 184
if i downgrade to 2.2.3 the problem seems solved

full crash log http://pastebin.com/JLisTP0P

**Comment by MysteriousAges** [comment]
Pressing 'u' on what? There isn't a lot in the log to go by. :|

**Comment by Crindigo** [comment]
It looks like outputCache is null the first time getOutput() is called in SpeciesRecipeManaInfusion. In my case, I pressed 'U' on an egg in my inventory when it crashed. The next time, I first browsed mana infusion recipes normally, with no crash, then after pressing U on the egg it worked fine.

**Comment by MysteriousAges** [comment]
Ohhhhhhhhhhhhhhhhhhhh bugger.

**Comment by MysteriousAges** [comment]
Will be fixed in next release version.
