### ISSUE TITLE
Different strings for Moon phases

### ISSUE THREAD

**Issue by Adaptivity** [MagicBees/MagicBees#54]
Is it possible to split phase names? 8 names for *research.requiresPhase* string and 8 for *research.requiresPhaseSingle*.
Or you can add some kind of custom names, so I'll able to write research.requiresPhaseFull, research.requiresPhasegibbousWaning etc.

**Comment by MysteriousAges** [comment]
The strings currently in the lang file accepts one or two phase parameters. Are these insufficient?

**Comment by Adaptivity** [comment]
Isn't all 8 phases used for *both* research.requiresPhase and research.requiresPhaseSingle? If no, can you say me which strings used for research.requiresPhase and which for research.requiresPhaseSingle?
And *if* for example phase *Full Moon* used for both it should be splitted, one for research.requiresPhase and one for research.requiresPhaseSingle. This is required for the proper translation into Russian for example.

**Comment by Adaptivity** [comment]
In other words: [these strings](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L175) can be used (for example) [here](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L200) in Russian language. BUT for [this entry](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L199) I need different strings, they not the same as for [this](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L199) in Russian laguage.

**Comment by MysteriousAges** [comment]
Ah, okay. I'm not sure it'll work well in code though... You can rephrase as much as you need, and can even re-order the format arguments if that'll help: 
```
%[argument_index$][flags][width][.precision]conversion
```

**Comment by Adaptivity** [comment]
@mezz please? :)

**Comment by MysteriousAges** [comment]
Not 100% sure this is what you need, since the phases will still be picked off programatically.

**Comment by Adaptivity** [comment]
Hmm, can you change them to something like *moon.alt.phasesingle.full*(these will be used for this [string](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L213) and *moon.alt.phase.full* (and this will be used for [this](https://github.com/MagicBees/MagicBees/blob/master/src/main/resources/assets/magicbees/lang/en_US.lang#L212)?

**Comment by MysteriousAges** [comment]
moon.X is used in both the moon dial for current phase, and the single phase mutations, moon.alt.X is used for the dual phase mutations.
