### ISSUE TITLE
Attuned bees spawn rate too low.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MagicBees/MagicBees#55]
I've mined for about 3 hours now in 3 MAGICAL classified biomes (Enchanted Forest (Twilight Forest), Cherry Blossom + Magical Forest (BoP)) and haven't found any hive to get the attuned bees....what's going on?

**Comment by Tukanen** [comment]
they're quite rare

**Comment by CrowAU** [comment]
They do spawn, I setup an ender quarry over a 150x150 area, by the time it finished i only got 2 attuned hives.

**Comment by mezz** [comment]
They only spawn between height 10 and 20 and require a spot with stone on all sides.
Seems like we should boost the spawn rate a bit.

**Comment by MysteriousAges** [comment]
Editing title. Might relax the location requirement a bit, and need to boost the frequency.
