### ISSUE TITLE
Tropical Queens/Princesses/Drones disappear

### ISSUE THREAD

**Issue by msegaud** [MagicBees/MagicBees#57]
I tried the new 2.3.0 release on a test world on the FTB Infinity 1.3.4 modpack. All tropical varieties of bees disappeared and are nowhere to be found in NEI. All genetic related stuff still exist but the bee seems to have been written out :)
Tested inoculation and other genetic ways of getting a tropical bee with the species serum but the bee just doesn't exist.

**Comment by MysteriousAges** [comment]
Did not encounter this in my testing, and can't replicate it on my end. Are you 100% sure there is nothing else in the pack mucking with Forestry?

**Comment by msegaud** [comment]
There must be, I'll wait for an update.

**Comment by MysteriousAges** [comment]
It's also possible you're getting shmucked by RNG, or a biome mod.
