### ISSUE TITLE
[Feature Request] Magnet in Bauble slot

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MagicBees/MagicBees#59]
Would be nice to have a config option to put the magnet in one of the bauble slots and freeing the inventory space.

**Comment by MysteriousAges** [comment]
Unsure if I want to depend on Baubles, since it would probably be a hard dependency.

**Comment by Unrepentant-Atheist** [comment]
doesn't have to be. Ender IO for example allows their Electromagnet to be in the bauble slot IF bauble is loaded. https://github.com/SleepyTrousers/EnderIO

Not sure where the code is, but maybe you can take a peek :)

**Comment by MysteriousAges** [comment]
Oh, that's neat. I'll look into it.

**Comment by Mementh** [comment]
I am curious what version this will be in? or is it supposed to be in already? if so how does one put it in (serious question since currently it can't be dropped in)

**Comment by MysteriousAges** [comment]
It's been in since September, but you have to have the Baubles mod active (standalone or bundled with another mod. MB doesn't bundle it.)
