### ISSUE TITLE
java.lang.AbstractMethodError: magicbees.bees.BeeMutation.getChance

### ISSUE THREAD

**Issue by Tsunayoshi** [MagicBees/MagicBees#60]
Hello!

I am getting a server crash with forestry 554 and magicbees magicbees-1.7.10-2.3.0

http://pastebin.com/efVGRH2f

forge 1401

**Comment by MysteriousAges** [comment]
Forestry 3.6.x+ contains breaking API changes.

Use the latest version available on CurseForge instead: http://minecraft.curseforge.com/mc-mods/59751-forestry

**Comment by mezz** [comment]
Forestry issue, fixed in latest unstable: https://github.com/ForestryMC/ForestryMC/issues/665
