### ISSUE TITLE
Fluxed Bee/Beealyzer crash

### ISSUE THREAD

**Issue by scain001** [MagicBees/MagicBees#64]
Originally posted this over at the Forestry mod, Mezz had a look and recommended I post here.

Original Post: When putting a fluxed queen into a the 3 slot in a beealyzer the game crashes, tested on both single and mulitplayer infinity pack. Also the secondary output used to be a fluxed electrum nugget, now there is a timer indicating a secondary output but no item is listed.

Crash Reports
https://gist.github.com/scain001/047905f428cd284d1891

**Comment by MysteriousAges** [comment]
Closed by 707266cad7b5d0cb5bba66c1dd235e2d42904f98
