### ISSUE TITLE
Aromatic lump doesnt craft

### ISSUE THREAD

**Issue by aubreybailey** [MagicBees/MagicBees#65]
The recipe listed in
MagicBees/src/main/java/magicbees/main/utils/CraftingManager.java
on lines
559-572
doesnt work for me.
Candles (just above) work fine.
It looks like the code here is pretty old, so I suspect that it is my fault, but I clearly tried enough variations to start reading code.
This will make my wife -very- happy.
Thanks!

**Comment by aubreybailey** [comment]
THANK YOU VERY MUCH!

**Comment by MysteriousAges** [comment]
np. It'll be fixed in 2.3.2, whenever that gets done.

**Comment by aubreybailey** [comment]
Np. I'll compile from this in the meantime :)
