### ISSUE TITLE
Osmium Producing Bees

### ISSUE THREAD

**Issue by Mortvana** [MagicBees/MagicBees#68]
Today, while working on updating an old modpack of mine, now that school is out, and I can stay up until 2:30am everyday, I thought, "Hey, I wish there was a bee that excreted tiny chunks of Osmium, as no mod has renewable Osmium production, and I know just the wereporcupine to add it!" If it will encourage you, I shall make a new sprite for the Doctorial Bee (don't ask how a bee has a long scarf, it just does :P)

EDIT: Fixed 1am typo

**Comment by MysteriousAges** [comment]
Closed by 71686766a9fed85d114e17db3eaa61cd91195319

Compat for Non-TConstruct Cobalt also added (naturalCobalt)

**Comment by Mortvana** [comment]
Thanks!
