### ISSUE TITLE
Add AppEng2 bees

### ISSUE THREAD

**Issue by MysteriousAges** [MagicBees/MagicBees#72]
Requested by @FireBall1725

 * [x] Certus - produce crystal
 * [x] Skystone
 * [x] Silicon
 * [x] Fluix

**Comment by grydian** [comment]
Any chance you can add fluix bees?  Could be a high tier bee hard to get to.  Just make the dust so they have to still grow the crystals.  Anyways just an idea :)

**Comment by MysteriousAges** [comment]
Sure, what the heck.

**Comment by grydian** [comment]
Awesome thanks man :D

**Comment by lshooter3k** [comment]
Doesn't AE2 use EnderIO silicon if it's added? And if so will it affect anything?

**Comment by MysteriousAges** [comment]
Can't get AE2 to run in dev.
Putting this on the backburner for now until I can resolve this.
