### ISSUE TITLE
[Suggestion] Blood Magic Bees

### ISSUE THREAD

**Issue by Selim042** [MagicBees/MagicBees#73]
I think the title explains it.

**Comment by MysteriousAges** [comment]
Uh, what would they do? There ARE Blood Magic bees already, but they don't DO anything.

**Comment by Dream-Master** [comment]
With Gendustry you can make your custom bees and combs  you whant via config.

**Comment by lshooter3k** [comment]
Probably complicated if even possible, but can you add a ritual that if an apiary is above it with a Bloody be in it will very slowly fill a nearby blood altar?

**Comment by hron84** [comment]
@TheModRipper it would be a good idea - especially if this connects to a sacrification thing, so bees sting any mob including player and slowly fill the alter.
