### ISSUE TITLE
Remove Mana steel Scoop, Mana Steel Grafter and Aelfheim bee trade from Botania entries

### ISSUE THREAD

**Issue by MysteriousAges** [MagicBees/MagicBees#74]
To appease @Vazkii, because people are idiots.

**Comment by heyoomimi** [comment]
What happened?

**Comment by mezz** [comment]
The entries were placed in the Botania book in a way that made it look like they were from Botania. 
Now they are separated into their own category so that it's obvious that they are from Magic Bees.
