### ISSUE TITLE
[Suggestion] Config to disable additional bees

### ISSUE THREAD

**Issue by SynfulChaot** [MagicBees/MagicBees#80]
Would it be possible for a config to use only the 'utility' part of the mod, such as the apiaries and flowers, without any of the additional bees?

**Comment by MysteriousAges** [comment]
Are you thinking of Binnie's Mods? MB doesn't add any flowers.

**Comment by SynfulChaot** [comment]
*Quite* sure I'm talking about Magic Bees, which has had flowers in the form of the Beegonia and Hiveacynth since 2.3.0 and the Hibeescus since 2.3.1.  I'd like to be able to use said flowers, as well as the Magic Apiary and the Thaumcraft and Botania tools without needing to add all the bees too.

**Comment by MysteriousAges** [comment]
Oh, I see what you're saying.

Currently, I'm not considering adding configs to disable chunks of the mod aside from other mod integration.
