### ISSUE TITLE
Add a config to disable certain bee branches

### ISSUE THREAD

**Issue by agroschim** [MagicBees/MagicBees#84]
I think it would be a good idea to add a config option to disable certain bee branches, i.e. the metallic and gem bees which are redundant if Extra Bees is installed.

**Comment by mezz** [comment]
Forestry's species blacklist config in `config/forestry/apiculture.cfg` should take care of this, you just need the UID of the bees you want to disable.

**Comment by MysteriousAges** [comment]
Also, I'm unlikely to add configs for disabling certain branches. EB does its own thing, MB does its.

**Comment by agroschim** [comment]
Thank's a lot! I did not know Forestry provided all the tools I needed!

**Comment by mezz** [comment]
There is an in-game command to dump a list of all bee UIDs, try some
commands listed in /forestry bee help

**Comment by MysteriousAges** [comment]
You can find all the MB ones starting here: https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/bees/BeeSpecies.java#L51 1st parameter for each entry, prefixed by "magicbees.species"

So, if you wanted to disable the Iron bees, for example, you can add "magicbees.speciesIron" to the Forestry blacklist to shut them off.
