### ISSUE TITLE
Reimplement high tier Thaumcraft bees with new effects

### ISSUE THREAD

**Issue by iarspider** [MagicBees/MagicBees#94]
NEI doesn't show any ways to get these. Dug through the code, and it looks like they are not made with any TC-y way either.

**Comment by MysteriousAges** [comment]
No, none of the upper tier of Thaumcraft bees are currently obtainable. The way nodes were handled in the switch from TC3 to TC4 b0rked them, and I never figured out a decent way to replace them, until recently. I'll be working on a replacement for them soon-ish.

**Comment by iarspider** [comment]
Thanks!

**Comment by MysteriousAges** [comment]
Closed with 7ae7af2238dcdcf6647fafe84b61501be010a31d
